spring:
  application:
    name: dbService
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:deal}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/create_tables.yml
server:
  port: 8081
logging:
  level:
    root: info
    bot.neoflex: debug
api:
  service:
    url: http://localhost:8082/api
management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    base-path: /actuator
